### ISSUE TITLE
Contact form settings/information stays empty.

### ISSUE THREAD

**Issue by iliyaM** [Way2CU/Caracal#35]
![screenshot from 2016-12-22 17-53-31](https://cloud.githubusercontent.com/assets/20294485/21431419/d2976d94-c86f-11e6-99dd-55ec090eab1a.png)

after the information is filled and saved, when reopening its empty again.

**Comment by iliyaM** [comment]
![screenshot from 2016-12-22 18-00-14](https://cloud.githubusercontent.com/assets/20294485/21431608/9576f136-c870-11e6-85c1-0bbfd0f0578f.png)

**Comment by MeanEYE** [comment]
Okay, this is Caracal bug. Thanks!

**Comment by MeanEYE** [comment]
@iliyaM please retest after updating and confirm.
