### ISSUE TITLE
Alignment of nav.mobile menu

### ISSUE THREAD

**Issue by iliyaM** [Way2CU/Caracal#44]
![screenshot from 2017-02-06 10-57-56](https://cloud.githubusercontent.com/assets/20294485/22640424/3b4e411e-ec5b-11e6-9565-2df7d612f0f8.png)

**Comment by MeanEYE** [comment]
Issue can be fixed by addressing outer box size instead of relying on jQuery's height.

**Comment by MeanEYE** [comment]
Old bug which I think was fixed, but surely not relevant anymore as it's hard to test.
