### ISSUE TITLE
Dialog's `set_size` is not working.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Caracal#65]
When dialog is called with `set_content_from_url` and `set_size`, size never gets set.

**Comment by MeanEYE** [comment]
@VladimirWebDev I need test for this. On either existing site with Dialog or empty site make a new dialog and call `set_size(400)` or something like that. I need to know if is reproducible.

**Comment by MeanEYE** [comment]
@VladimirWebDev what's the result of this test?

**Comment by VladimirWebDev** [comment]
When calling method and passing dimensions, you have to specify unit. 
set_size("400px", "200px");
If px is omitted (or other unit), method is not working.

**Comment by MeanEYE** [comment]
Okay thanks!
